-- Scan run summary (per subreddit)
create table if not exists public.scan_runs (
  id bigint generated by default as identity primary key,
  run_id text not null,
  account text not null,
  timestamp_utc timestamptz not null,
  timestamp_local timestamptz,
  timezone text,
  scan_window text,
  mode text,
  subreddit text not null,
  posts_scanned integer not null default 0,
  matches_logged integer not null default 0,
  scan_sort text,
  scan_time_range text,
  scan_page_offset integer default 0,
  subreddit_set text,
  ingested_at timestamptz not null default now()
);

create unique index if not exists scan_runs_unique
  on public.scan_runs (run_id, account, subreddit);

create index if not exists scan_runs_subreddit
  on public.scan_runs (subreddit);


-- Raw scan events (one row per matched post)
create table if not exists public.scan_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  run_id text not null,
  account text not null,
  timestamp_utc timestamptz not null,
  timestamp_local timestamptz,
  timezone text,
  scan_window text,
  mode text,
  subreddit text,
  post_id text,
  title text,
  matched_keywords jsonb,
  url text,
  method text,
  status text,
  scan_sort text,
  scan_time_range text,
  scan_page_offset integer default 0,
  subreddit_set text,
  ingested_at timestamptz not null default now()
);

create unique index if not exists scan_events_event_key
  on public.scan_events (event_key);

create index if not exists scan_events_post_id
  on public.scan_events (post_id);

create index if not exists scan_events_url
  on public.scan_events (url);

create index if not exists scan_events_subreddit
  on public.scan_events (subreddit);

create index if not exists scan_events_timestamp
  on public.scan_events (timestamp_utc);


-- Aggregated view for easy Render queries
create or replace view public.scanned_posts as
select
  coalesce(nullif(url, ''), nullif(post_id, ''), title) as post_key,
  max(url) as url,
  max(post_id) as post_id,
  max(subreddit) as subreddit,
  max(title) as title,
  min(timestamp_utc) as first_seen_at,
  max(timestamp_utc) as last_seen_at,
  count(*) as seen_count,
  array_agg(distinct kw) filter (where kw is not null) as matched_keywords
from public.scan_events
left join lateral jsonb_array_elements_text(matched_keywords) as kw on true
group by post_key;
